  module.exports = {
        SIDENAVBAR :"sidenavbar",
        SEARCH:"search",
        JOBS : "jobs",
        ADMINS :"admins",
        COORDINATORS : "coordinator",
        SUPERVISORS :"supervisors",
        CANDIDATES : "candidates",
        CANDIDATE :"candidate",
        ADMIN :"admin",
        SUPERVISOR:"supervisor",
        COORDINATOR : "coordinator",
        CREATE : "create",
        EDIT : "edit",
        DELETE : "delete",
        READ : "read",
        IMPORTS:"imports",
        JOBPROVIDER :"jobprovider",
        REPORTS :'reports',
        SEARCHCANDIDATE : 'searchcandidate',
        // JOBPOST :"jobpost",
        PERSONALINFO:"personalinfo",
        JOBPREFERENCES:"jobpreferences",
        EDUCATION:"education",
        SKILLS:"skills",
        WORKEXPERIENCE:"workexperience",
        // GALLERY:"gallery",
        PROJECTS:"projects",
        COORDINATORUSERS : "coordinatorusers",
        COORDINATORS : "coordinators",
        CENTERDETAILS:"centerdetails",
        SKILLCARD :"skillcard"
  }
