  module.exports = {
        SIDENAVBAR :"sidenavbar",
        SEARCH:"search",
        JOBS : "jobs",
        ADMIN :"admin",
        COORDINATOR : "coordinator",
        SUPERVISOR :"supervisor",
        CANDIDATE : "candidate",
        CREATE : "create",
        EDIT : "edit",
        DELETE : "delete",
        READ : "read",
        // RBAC:"rbac",
        JOBPROVIDER :"jobprovider",
        PERSONINFO:"personalinfo",
        JOBPREFERENCES:"jobpreferences",
        EDUCATION:"education",
        SKILLS:"skills",
        WORKEXPERIENCE:"workexperience",
        // GALLERY:"gallery",
        PROJECTS:"projects",
        COORDINATORUSERS : "coordinatorusers",
        COORDINATORS : "coordinators",
        CENTERDETAILS:"centerdetails"
  }
